LOADER:
  DATASET: 'cifar100'
  NUM_CLASSES: 100
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  USE_VAL: True
  TRANSFORM: "default"
OPTIM:
  BASE_LR: 0.2
  WEIGHT_DECAY: 1.e-4
  MAX_EPOCH: 40
TRAIN:
  IM_SIZE: 32
TEST:
  IM_SIZE: 32
POST:
  PATH: "weights/dbb_cycle_c100.pyth"
  WARMUP: 20
  ALPHA: 0.5
  TEMPERATURE: 4.
  DBB_TYPE: 'DBB'
  TEACHER_PATH: 'weights/resnet101.pth'