LOADER:
  DATASET: 'imagenet'
  NUM_CLASSES: 1000
  BATCH_SIZE: 256
  NUM_WORKERS: 24
  USE_VAL: True
  TRANSFORM: "auto_augment_tf"  # "default"
OPTIM:
  BASE_LR: 0.3
  WEIGHT_DECAY: 3.e-5
  MAX_EPOCH: 120
TRAIN:
  IM_SIZE: 224
TEST:
  IM_SIZE: 224
POST:
  TEACHER: "efficientnet_b4"
  PATH: "weights/IMG_dbb.pyth"
  WARMUP: 40
  ALPHA: 0.1
  TEMPERATURE: 1.
NUM_GPUS: 4