LOADER:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  USE_VAL: True
  TRANSFORM: "default"
OPTIM:
  BASE_LR: 0.2
  WEIGHT_DECAY: 1.e-4
  MAX_EPOCH: 160
TRAIN:
  IM_SIZE: 32
TEST:
  IM_SIZE: 32