LOADER:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  USE_VAL: True
  TRANSFORM: "default"
OPTIM:
  BASE_LR: 0.75
  WEIGHT_DECAY: 2.e-4
  MAX_EPOCH: 30
TRAIN:
  IM_SIZE: 32
TEST:
  IM_SIZE: 32
POST:
  PATH: "weights/repvgg.pyth"
  WARMUP: 20
  ALPHA: 0.9
  TEMPERATURE: 10.