LOADER:
  DATASET: 'cifar100'
  NUM_CLASSES: 100
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  USE_VAL: True
  TRANSFORM: "default"
OPTIM:
  BASE_LR: 0.2
  WEIGHT_DECAY: 2.e-4
  MAX_EPOCH: 160
TRAIN:
  IM_SIZE: 32
TEST:
  IM_SIZE: 32
POST:
  ALPHA: 0.1
  TEMPERATURE: 4.